apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-mysql
spec:
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: secret-mysql
                    key: MYSQL_ROOT_PASSWORD
          envFrom:
            - configMapRef:
                name: cm-mysql
          volumeMounts:
            - name: volume-mysql
              mountPath: /var/lib/mysql
      volumes:
        - name: volume-mysql
          persistentVolumeClaim:
            claimName: pvc-mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: svc-mysql