apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sistema-noticias
spec:
  template:
    metadata:
      name: sistema-noticias
      labels:
        app: sistema-noticias
    spec:
      containers:
        - name: sistema-noticias-container
          image: aluracursos/sistema-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cm-sistema-noticias
  replicas: 4
  selector:
    matchLabels:
      app: sistema-noticias