apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-db-noticias
spec:  
  template:
    metadata:
      name: db-noticias
      labels:
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: cm-db-noticias
  replicas: 2
  selector:
    matchLabels:
      app: db-noticias