apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-portal-noticias
spec:
  replicas: 1
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: cm-portal-noticias
          resources:
            requests:
              cpu: 10m
  selector:
    matchLabels:
      app: portal-noticias